ForumMVC/Controllers/ForumController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ForumMVC.Models;

namespace ForumMVC.Controllers
{
    public class ForumController : Controller
    {
        //
        // GET: /Forum/

        ForumDB forumDB = new ForumDB();

        public ActionResult Index()
        {
            var mainTopics = forumDB.MainTopics.ToList();
            return View(mainTopics);
        }
        public ActionResult Browse(string mainTopic)
        {
            var mainTopicModel = forumDB.MainTopics.Include("SecondTopics").Single(s => s.Name == mainTopic);
            return View(mainTopicModel);
        }
        public ActionResult Details(int id)
        {
            var secondTopic = forumDB.SecondTopics.Find(id);
            return View(secondTopic);
        }
        [ChildActionOnly]
        public ActionResult MainTopicMenu()
        {
            var maintopics = forumDB.MainTopics.ToList();
            return PartialView(maintopics);
        }
    
    }
}

ForumMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Scripts/jquery-1.5.1.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/modernizr-1.7.min.js")" type="text/javascript"></script>
</head>

<body>
<div id="header">
   <h1><a href="/">ASP.NET MVC FORUM</a></h1>
    @Html.Partial("_LogOnPartial")
   <ul id="navlist">
       <li class="first"><a href="@Url.Content("~") id="current">Home</a></li>
       <li><a href="@Url.Content("~/Forum/")">Forum</a></li>
       <li><a href="@Url.Content("~/ForumManager/")">Admin</a></li>  </ul>
</div>
    @{Html.RenderAction("MainTopicMenu", "Forum");}
    <div id="main"> @RenderBody()
</div>
<div id="footer">
<p>
Aleksandar Arnaudov</p>
</div>
</body>
</html>

ForumMVC/Views/Shared/_LogOnPartial.cshtml
@if(Request.IsAuthenticated) {
    <text>Welcome <strong>@User.Identity.Name</strong>!
    [ @Html.ActionLink("Log Off", "LogOff", "Account") ]</text>
}
else {
    @:[ @Html.ActionLink("Log On", "LogOn", "Account") ]
}